server:
  port: 9099


spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///carbon
  redis:
    port: 6379
    host: localhost




logging:
  level:
    com.carbon: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
